name: notify release
on:
  workflow_call:
    inputs:
      version:
        description: 'Java SDK Version'
        required: true
        type: string

  workflow_dispatch:
    inputs:
      manual_java_sdk_version:
        description: 'Java SDK Version (Only for testing)'
        required: false
jobs:
  notify_hackle_java_sdk_release:
    runs-on: ubuntu-latest
    steps:
      - name: Set version
        id: version
        env:
          VERSION: ${{ inputs.version || inputs.manual_java_sdk_version }}
        run: |
          echo "java_sdk_version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.DEPLOY_CLIENT_ID }}
          private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: hackle-android-sdk
          permission-actions: write

      - name: Trigger hackle-android-sdk workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update core sdk
          repo: hackle-io/hackle-android-sdk
          ref: main
          token: ${{ steps.app-token.outputs.token }}
          inputs: '{ "core_version": "${{ steps.version.outputs.java_sdk_version }}" }'
